mrlesmithjr/dockerfiles

- .github/workflows/centos-7-publish.yml
- .github/workflows/centos-8-publish.yml
- .github/workflows/debian-10-publish.yml
- .github/workflows/debian-11-publish.yml
- .github/workflows/ubuntu-1804-publish.yml
- .github/workflows/ubuntu-2004-publish.yml
> Add push to Docker Hub

- .github/workflows/centos-7.yml
- .github/workflows/centos-8.yml
- .github/workflows/debian-10.yml
- .github/workflows/debian-11.yml
- .github/workflows/ubuntu-1804.yml
- .github/workflows/ubuntu-2004.yml
> Test additional architectures

- .github/workflows/alpine-313-publish.yml
- .github/workflows/alpine-313.yml
- .github/workflows/alpine-314-publish.yml
- .github/workflows/alpine-314.yml
- alpine/3.13/Dockerfile
- alpine/3.14/Dockerfile
> Add Alpine Linux

- .github/workflows/alpine-313-publish.yml
- .github/workflows/alpine-314-publish.yml
> Fix Docker Hub pushes

- .github/workflows/fedora-34-publish.yml
- .github/workflows/fedora-34.yml
- .github/workflows/fedora-35-publish.yml
- .github/workflows/fedora-35.yml
- fedora/34/Dockerfile
- fedora/35/Dockerfile
> Add Fedora Linux

- .github/workflows/rocky-8-publish.yml
- .github/workflows/rocky-8.yml
- rocky/8/Dockerfile
> Add Rocky Linux

- .github/workflows/ubuntu-1604-publish.yml
- .github/workflows/ubuntu-1604.yml
- ubuntu/16.04/Dockerfile
> Add Ubuntu 16.04

- .github/workflows/debian-9-publish.yml
- .github/workflows/debian-9.yml
- debian/9/Dockerfile
> Add Debian 9

- .github/workflows/debian-8-publish.yml
- .github/workflows/debian-8.yml
- debian/8/Dockerfile
> Add Debian 8

- debian/8/Dockerfile
> Revert Debian 8 Python Version

- .github/workflows/alpine-313-publish.yml
- .github/workflows/alpine-313.yml
- .github/workflows/alpine-314-publish.yml
- .github/workflows/alpine-314.yml
- .github/workflows/centos-7-publish.yml
- .github/workflows/centos-7.yml
- .github/workflows/centos-8-publish.yml
- .github/workflows/centos-8.yml
- .github/workflows/debian-10-publish.yml
- .github/workflows/debian-10.yml
- .github/workflows/debian-11-publish.yml
- .github/workflows/debian-11.yml
- .github/workflows/debian-8-publish.yml
- .github/workflows/debian-8.yml
- .github/workflows/debian-9-publish.yml
- .github/workflows/debian-9.yml
- .github/workflows/fedora-34-publish.yml
- .github/workflows/fedora-34.yml
- .github/workflows/fedora-35-publish.yml
- .github/workflows/fedora-35.yml
- .github/workflows/rocky-8-publish.yml
- .github/workflows/rocky-8.yml
- .github/workflows/ubuntu-1604-publish.yml
- .github/workflows/ubuntu-1604.yml
- .github/workflows/ubuntu-1804-publish.yml
- .github/workflows/ubuntu-1804.yml
- .github/workflows/ubuntu-2004-publish.yml
- .github/workflows/ubuntu-2004.yml
> Fix workflow paths to watch

- .github/config.yml
- .github/release-drafter.yml
- .github/settings.yml
- .github/stale.yml
- .github/workflows/release-drafter.yml
> Add additional GitHub config(s)

- centos/8/Dockerfile
> Change to quay.io/centos/centos:stream8

- centos/7/Dockerfile
> Centos7 quay.io

- .github/workflows/centos-9-publish.yml
- .github/workflows/centos-9.yml
- centos/9/Dockerfile
> CentOS Stream 9

- .pre-commit-config.yaml
- centos/8/Dockerfile
- centos/9/Dockerfile
> CentOS 8/9 build errors

- .github/workflows/ubuntu-2204-publish.yml
- .github/workflows/ubuntu-2204.yml
- ubuntu/22.04/Dockerfile
> Ubuntu2204

- .github/workflows/fedora-37-publish.yml
- .github/workflows/fedora-37.yml
> Added missing Fedora 37 workflows

- .github/workflows/fedora-38-publish.yml
- .github/workflows/fedora-38.yml
- fedora/38/Dockerfile
> Add Fedora 38

- .github/workflows/debian-12-publish.yml
- .github/workflows/debian-12.yml
- debian/12/Dockerfile
Add Debian 12
needed for https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/pull/171
> Add Debian 12

- ubuntu/24.04/Dockerfile
add ubuntu 24.04 to prepare container for MariaDB repo
> add ubuntu 24.04
